# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  {C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.srcs/sources_1/new/Encryption.vhd}
  {C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.srcs/sources_1/new/main.vhd}
}
read_xdc {{C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.srcs/constrs_1/imports/new/constraint.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Kevin/Downloads/CPE 350 Capstone/BasysAES.srcs/constrs_1/imports/new/constraint.xdc}}]

synth_design -top main -part xc7a35tcpg236-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
